packages:
  - "."
  - "packages/*"
allowBuilds:
  '@parcel/watcher': true
  core-js: true
  dtrace-provider: true
  es5-ext: true
  esbuild: true
  msw: true
  sharp: true
  spawn-sync: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - dtrace-provider
  - es5-ext
  - esbuild
  - fsevents
  - msw
  - sharp
  - spawn-sync
